Migration content update
MicrosoftDocs/microsoftgraph-docs-powershell pull request #103
Opened 2022-08-19 08:47 UTC by msewaweru

2022-08-19 08:55 UTC, opbld31 commented
Docs Build status updates of commit _[d2d2b2b](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/d2d2b2b577bfe75fb520fbbda64e4e48b506173b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202208190847222335-103/BuildReport?accessString=44ba6812e2ea99e53df583bf4bb60e8a39dee5c7eb07f90ef85919a65b2de2e5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 08:36 UTC, opbld31 commented
Docs Build status updates of commit _[0ace911](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/0ace9116969726647194c497ee1c1b27520cead7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202208300828114399-103/BuildReport?accessString=d14f35006564c4e97aa38417a7b43033deda719cf3c8eba5deff8c79d77a5160).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-30 10:14 UTC, opbld32 commented
Docs Build status updates of commit _[3b2fdd3](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/3b2fdd319c26ba3e3cfda6246af45f5ac36a9b8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202208301005237459-103/BuildReport?accessString=65cce036fae253c499d7086c6b921316555b5259923b8b8ac645fcdea240a49f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-31 10:50 UTC, opbld33 commented
Docs Build status updates of commit _[2de45df](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/2de45df3de5ed3d480340e13f9e12536ba5b01c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202208311040351361-103/BuildReport?accessString=0d759c94b909879aecf36b6b24ce4a30d2bf32ee7198b814e009a781276996b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 07:02 UTC, opbld30 commented
Docs Build status updates of commit _[77b9d03](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/77b9d03f1ba99fb59c6122454bb4ff06bb25961d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209020653481808-103/BuildReport?accessString=4232c567a0593d2b9a8ddf37a75c34af71b3b9a45bb18993a563935d3f752130).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 07:23 UTC, opbld33 commented
Docs Build status updates of commit _[b1b966d](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/b1b966dc12944d69bbb770b2cf5edba09cd3b656)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209020714252733-103/BuildReport?accessString=9f9fb4b1dc38509ffe5b15ba2bce443b7d842c7a182a2a6dfc4e2c10926b0c69).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-02 07:55 UTC, msewaweru commented
Hi @f4rty - this is ready for your review.

2022-09-06 14:15 UTC, opbld31 commented
Docs Build status updates of commit _[1f51698](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/1f51698d45c5b85c04de19bf47de507a7671274a)_: 

### :bulb: Validation status: suggestions


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) | [Details](#user-content-f4b7cc795da95323db111a51ada52437-e62a6edc)
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

<a id="f4b7cc795da95323db111a51ada52437-e62a6edc"></a>
### [microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md)
 - **Line 50, Column 220**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /powershell/module/psscriptanalyzer/?view=ps-modules`````
 - **Line 69, Column 15**: **[Suggestion: preserve-view-not-set - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````You've pinned this link to a specific version of content with the view parameter. It's recommended not to pin a version unless that version is A) not the default view and B) the context is about that version specifically. To proceed with pinning a version add the &preserve-view=true to the URL.  Otherwise, remove the view parameter. URL: /graph/api/overview?view=graph-rest-1.0`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209061406566061-103/BuildReport?accessString=2c8f69dff969484e0d3213b2e67ca65e4e06c12f82b74489928506bb72b9171d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 08:23 UTC, opbld33 commented
Docs Build status updates of commit _[936f98c](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/936f98cf135332e458418d5767eef488cce6e1f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209070814105992-103/BuildReport?accessString=19f29d8d8a5992f36ad75f27f12505d7fe3a0f56dc672feb8062a6c02496db78).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 08:39 UTC, opbld33 commented
Docs Build status updates of commit _[b517567](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/b51756712eee3fa868855ce7169b383c4ce47c69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209070830209007-103/BuildReport?accessString=22151d4dd61f7f01a57f72897411373f948eb8d751db694ded5020b47875fb9c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 08:54 UTC, opbld32 commented
Docs Build status updates of commit _[17e768a](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/17e768a949aff912ce2ba6bce7e4729643a1343f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209070846142473-103/BuildReport?accessString=46da35f72762e274ca522b58c6c373097327bd9b7afc67544a89c5285e876357).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-07 09:10 UTC, msewaweru commented
@f4rty, please review this. I have incorporated feedback from our discussions. Thanks.

2022-09-09 06:57 UTC, opbld33 commented
Docs Build status updates of commit _[3ef4005](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/3ef4005e28524e5584ac80c884f2f7f5f255d57f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209090649150564-103/BuildReport?accessString=f347623f4f2a68179ca970c9d9b9de563b2e4ca8b5475302dd3dc17051bd3016).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-09 07:20 UTC, opbld30 commented
Docs Build status updates of commit _[b7f8ea9](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/b7f8ea9ffe4399da84774e44dee66c3c4386f2b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/migration-steps.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/migration-steps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/toc.yml](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/migration-content-update/microsoftgraph/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/powershell/microsoftgraph/migration-steps?view=graph-powershell-1.0&branch=pr-en-us-103) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202209090711574421-103/BuildReport?accessString=d8d0f7da6f3ba628b2ff78fc682520ef9c64d41f084d4a08d16c636e781636e0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-15 08:35 UTC, f4rty commented
Reviewed and approved

2022-09-15 11:02 UTC, msewaweru commented
@adamedx , requesting for your review of the updated migration content. Thanks.

2022-09-19 22:36 UTC, adamedx requested changes
This is a good start, though I think we may need something more in-depth soon.

2022-09-19 22:36 UTC, adamedx commented on microsoftgraph/docs-conceptual/migration-steps.md
> +Azure AD, Azure AD Preview and MSOnline PowerShell modules are planned for deprecation. Microsoft Graph PowerShell is the recommended PowerShell module for interacting with Azure AD and other Microso
I feel like this should be stronger -- it's not just "recommended" -- this is the module to use period. It's certainly the case that the previous modules are no longer being updated and do not support new APIs.

2022-09-19 22:36 UTC, adamedx commented on microsoftgraph/docs-conceptual/migration-steps.md
> +- Search doesn't yet work for any Azure AD commands.
This is not true -- Search works for many commands such as `Get-MgUser` -- as long as you use `ConsistencyLevel` of `Eventual`. The behavior is not the same as `SearchString` but arguably better.

2022-09-20 12:36 UTC, opbld33 commented
Docs Build status updates of commit _[f058921](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/f0589210b499fc0d68730f5fca95d0be01779c9d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-21 09:22 UTC, msewaweru commented
@timayabi2020, please merge this.

2022-09-21 09:55 UTC, timayabi2020 approved these changes

2022-09-21 09:55 UTC, merged