Metadata clean up for the articles
MicrosoftDocs/microsoftgraph-docs-powershell pull request #134
Opened 2022-09-28 08:25 UTC by msewaweru

2022-10-24 18:00 UTC, msewaweru commented
> @msewaweru - What's your ETA on this PR? Thanks.

Hi @CelesteDG, looking to conclude this work within this week. Thanks.

2022-10-26 12:04 UTC, opbld33 commented
Learn Build status updates of commit _[fcc6063](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/fcc6063786be5efb65f84aa778a9e2ac9e164461)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-82a1b54f)

<a id="82a1b54f"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit fcc6063786be5efb65f84aa778a9e2ac9e164461 in branch mstopic of repository https://github.com/msewaweru/microsoftgraph-docs-powershell into branch main (commit 09954b65dce34ce7051b6b7e5bc179511cb33dda). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202210261204106249-134/BuildReport?accessString=5471d7999048c73a8a36e06c7e2ef8c68d0169f0570c9261f4423b28f873b72a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 12:19 UTC, opbld32 commented
Learn Build status updates of commit _[93ced4a](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/93ced4adffa1755f6749df289e8e6ff676859904)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/app-only.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/app-only.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/app-only?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/find-mg-graph-command.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/find-mg-graph-command.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/find-mg-graph-permission.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/find-mg-graph-permission.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-permission?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/get-started.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/get-started.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/installation.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/navigating.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/navigating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/navigating?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202210261209090491-134/BuildReport?accessString=851fabe8968d3758a0bde5254f27eee44c160c9bd996edb89eda3bc4a12e93af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-26 16:47 UTC, CelesteDG requested changes
Just some minor tweaks. Thank you.

2022-10-26 16:47 UTC, CelesteDG commented on microsoftgraph/docs-conceptual/app-only.md
>  author: jasonjoh
@msewaweru Please add the manager field here. It's not so much direct manager as business owner, M1 PoC for the article in terms of reporting, escalation, etc. Can put me here and for the others with Jason as author. Thank you.

2022-10-27 08:02 UTC, opbld31 commented
Learn Build status updates of commit _[3fa1e01](https://github.com/msewaweru/microsoftgraph-docs-powershell/commits/3fa1e016aec756f8becbe2eb83fd9f3dde0707c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[microsoftgraph/docs-conceptual/app-only.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/app-only.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/app-only?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/find-mg-graph-command.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/find-mg-graph-command.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/find-mg-graph-permission.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/find-mg-graph-permission.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-permission?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/get-started.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/get-started.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/installation.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/installation.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |
[microsoftgraph/docs-conceptual/navigating.md](https://github.com/msewaweru/microsoftgraph-docs-powershell/blob/mstopic/microsoftgraph/docs-conceptual/navigating.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/powershell/microsoftgraph/navigating?view=graph-powershell-1.0&branch=pr-en-us-134) (graph-powershell-1.0 \|\| graph-powershell-beta) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/c847a38e-33de-63ed-4ac9-5917fc04e540/202210270752302082-134/BuildReport?accessString=d4749091cc75a4d28ad384c487eba659cc4510c16227dd62e72b616571d81057).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/c847a38e-33de-63ed-4ac9-5917fc04e540?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 12:27 UTC, msewaweru commented
@CelesteDG, changes made and ready for merging. Thanks.

2022-10-28 07:50 UTC, msewaweru commented
@mwongerapk, please merge this.

2022-11-01 16:56 UTC, merged